export const products = [
  {
    id: "1",
    name: "The Original Unisex leather",
    price: 250.0,
    oldPrice: 350.0,
    image: "/images/product_1.png",
    category: "Unisex",
    tag: "New",
    brand: "Titanium",
    rating: 4.8,
    reviews: 124,
    description:
      "A masterpiece of minimalism. The Original Unisex Leather watch features a clean white dial housed in a polished silver case, paired with a premium genuine leather strap that ages beautifully over time. Perfect for both casual and formal occasions.",
    specs: [
      { label: "Brand", value: "Titanium" },
      { label: "Strap Material", value: "Genuine Leather" },
      { label: "Glass Material", value: "Sapphire Crystal" },
      { label: "Strap Color", value: "Tan / Brown" },
      { label: "Movement", value: "Japanese Quartz" },
      { label: "Water Resistance", value: "5 ATM" },
      { label: "Case Size", value: "40 mm" },
      { label: "Warranty", value: "2 Years" },
    ],
  },
  {
    id: "2",
    name: "Tri-Tone Rose-tone Leather",
    price: 250.0,
    image: "/images/product_2.png",
    category: "Women",
    tag: "Best Seller",
    brand: "Titanium",
    rating: 4.9,
    reviews: 89,
    description:
      "Elegant and sophisticated, the Tri-Tone Rose-tone watch combines soft rose gold accents with a luxurious leather strap. The mother-of-pearl dial adds a touch of high fashion to your wrist.",
    specs: [
      { label: "Brand", value: "Titanium" },
      { label: "Strap Material", value: "Premium Leather" },
      { label: "Glass Material", value: "Mineral Glass" },
      { label: "Strap Color", value: "Dark Brown" },
      { label: "Movement", value: "Swiss Quartz" },
      { label: "Water Resistance", value: "3 ATM" },
      { label: "Case Size", value: "34 mm" },
      { label: "Warranty", value: "2 Years" },
    ],
  },
  {
    id: "3",
    name: "Christal Automatic Steel",
    price: 230.0,
    image: "/images/product_3.png",
    category: "Men",
    tag: "Sale",
    brand: "Kobold",
    rating: 4.7,
    reviews: 56,
    description:
      "Rugged durability meets refined style. The Christal Automatic features a striking blue sunburst dial and a robust stainless steel bracelet. Powered by a reliable automatic movement.",
    specs: [
      { label: "Brand", value: "Kobold" },
      { label: "Strap Material", value: "Stainless Steel" },
      { label: "Glass Material", value: "Sapphire Crystal" },
      { label: "Strap Color", value: "Silver" },
      { label: "Movement", value: "Automatic" },
      { label: "Water Resistance", value: "10 ATM" },
      { label: "Case Size", value: "42 mm" },
      { label: "Warranty", value: "3 Years" },
    ],
  },
  {
    id: "4",
    name: "Black & gold michael kors",
    price: 290.0,
    image: "/images/product_4.png",
    category: "Men",
    tag: "New",
    brand: "Aurum & Noir",
    rating: 5.0,
    reviews: 210,
    description:
      "Bold and commanding. This chronograph watch features a matte black finish with striking gold accents. Designed for the modern man who appreciates precision and presence.",
    specs: [
      { label: "Brand", value: "Aurum & Noir" },
      { label: "Strap Material", value: "Stainless Steel / PVD" },
      { label: "Glass Material", value: "Sapphire Crystal" },
      { label: "Strap Color", value: "Black & Gold" },
      { label: "Movement", value: "Chronograph Quartz" },
      { label: "Water Resistance", value: "10 ATM" },
      { label: "Case Size", value: "44 mm" },
      { label: "Warranty", value: "2 Years" },
    ],
  },
  {
    id: "5",
    name: "Michael kors watches rose gold",
    price: 250.0,
    image: "/images/product_5.png",
    category: "Women",
    tag: "Featured",
    brand: "Titanium",
    rating: 4.8,
    reviews: 145,
    description:
      "Intricate skeleton dial meets rose gold elegance. This timepiece serves as both a functional watch and a stunning piece of jewelry, revealing the complex mechanics within.",
    specs: [
      { label: "Brand", value: "Titanium" },
      { label: "Strap Material", value: "Mesh Steel" },
      { label: "Glass Material", value: "Sapphire Crystal" },
      { label: "Strap Color", value: "Rose Gold" },
      { label: "Movement", value: "Automatic Skeleton" },
      { label: "Water Resistance", value: "3 ATM" },
      { label: "Case Size", value: "36 mm" },
      { label: "Warranty", value: "2 Years" },
    ],
  },
];

export const navLinks = [
  { name: "HOME", href: "/" },
  { name: "CATEGORIES", href: "/categories" },
  { name: "WOMEN", href: "/women" },
  { name: "MEN", href: "/men" },
  { name: "TOP SALE", href: "/sale" },
  { name: "BLOG", href: "/blog" },
  { name: "CONTACT", href: "/contact" },
];
